### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Kool-Cool** [lokendarjangid/gemini-chat#14]
https://github.com/lokendarjangid/gemini-chat/blob/2d4883111b83c927b00c51aa236b35ea451e383b/README.md?plain=1#L27-L30

use 
```md
git clone https://github.com/lokendarjangid/gemini-chat.git

```

**Comment by Kool-Cool** [comment]
https://github.com/lokendarjangid/gemini-chat/blob/2d4883111b83c927b00c51aa236b35ea451e383b/README.md?plain=1#L32-L37


use
```md
cd gemini-chat
```

**Comment by lokendarjangid** [comment]
#7 it is already there no need to create a another issue for these changes

**Comment by lokendarjangid** [comment]
@Kool-Cool you can make a pull request over there

**Comment by JudahNii** [comment]
I can update the README file

**Comment by lokendarjangid** [comment]
yes you can

**Comment by lokendarjangid** [comment]
@JudahNii make pr for that

**Comment by JudahNii** [comment]
> @JudahNii make pr for that

Pull request has been made.

**Comment by lokendarjangid** [comment]
@JudahNii next time link the issue with the pull request

**Comment by JudahNii** [comment]
> @JudahNii next time link the issue with the pull request

I will do that next time. Thank you.

**Comment by lokendarjangid** [comment]
done
