### ISSUE TITLE
increase the width of containers

### ISSUE THREAD

**Issue by lokendarjangid** [lokendarjangid/gemini-chat#23]
increase the width of the 
* output container
* input container

or remove margin from container or remove the padding from body

for the mobile screen

![Screenshot from 2024-01-05 22-06-13](https://github.com/lokendarjangid/gemini-chat/assets/57801045/e0a954a2-1469-4bac-b8fd-ee1cee3705eb)

**Comment by OsafAliSayed** [comment]
hi, I am looking into this issue. I don't the padding or margin is the issue here

**Comment by lokendarjangid** [comment]
@OsafAliSayed go ahead i assigned this to you

**Comment by lokendarjangid** [comment]
@OsafAliSayed if you see any type of issue in this project please make an issue for that
