### ISSUE TITLE
clear session or variable when tab closed

### ISSUE THREAD

**Issue by lokendarjangid** [lokendarjangid/gemini-chat#29]
when user closes the tab before that a function should be called `clear_session` 

variable name is session data is `output_dict` in app.py file

modify the code in :

- static/script.js

**Comment by codeIntrovert** [comment]
I can do that... whenever user closes the website a function needs to be called `clear_session` in app.py. Can you Assign me this issue, I'll take a look

**Comment by lokendarjangid** [comment]
You can look into this issue

**Comment by codeIntrovert** [comment]
Sorry for the delay, Starting Development, will fix this today itself

**Comment by lokendarjangid** [comment]
Thank you

**Comment by codeIntrovert** [comment]
Completed pull request #49
